spring:
  application:
    name: Academy_CRUD_API
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=academy
  jpa:
    properties:
      hibernate:
        default_schema: academy
        format_sql: false
        show_sql: true
        hbm2ddl:
          auto: update


